import {StyleSheet, Dimensions, Platform} from 'react-native';
import {
  BGGRAY,
  BLACK,
  BUILDRR_BLUE,
  LIGHTGRAY,
  PRIMARY_COLOR,
  SECONDARY,
  WHITE,
  YELLOW,
} from '../../constants/Colors';
import constants from '../../constants';

const HEIGHT = constants.BaseStyle.DEVICE_HEIGHT / 100;
const WIDTH = constants.BaseStyle.DEVICE_WIDTH / 100;

var {width, height} = Dimensions.get('window');

const CommonStyles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
    backgroundColor: WHITE,
  },

  mainContainer: {
    flex: 1,
    paddingHorizontal: WIDTH * 5,
    backgroundColor: WHITE,
  },
  mainContainerWithoutBG: {
    flex: 1,
    paddingHorizontal: WIDTH * 5,
  },
  safeAreaView: {
    flex: 1,
    // justifyContent: "center",
    // alignItems: "center",
    backgroundColor: 'WHITE',
  },
  safeAreaView2: {
    flex: 1,
    backgroundColor: WHITE,
  },
  flexRow: {
    width: WIDTH * 1,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: SECONDARY,
  },
  defaultHeader: {
    backgroundColor: PRIMARY_COLOR,
    elevation: 0,
    shadowOpacity: 0,
  },
  defaultHeaderTitle: {},
  headerLeftView: {
    paddingVertical: 5,
    height: 40,
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpIconStyle: {
    height: HEIGHT * 15,
    width: HEIGHT * 10,
    alignSelf: 'center',
    marginTop: HEIGHT * 5,
  },
  lineView: {
    height: 1,
    backgroundColor: '#E5E5E6',
  },
  loginInputView: {
    borderWidth: 1,
    width: WIDTH * 90,
    alignSelf: 'center',
    borderColor: '#7C7C80' + 50,
    height: 50,
    paddingHorizontal: WIDTH * 5,
    borderRadius: 5,
  },
  updateButton: {
    backgroundColor: BUILDRR_BLUE,
    alignItems: 'center',
    paddingVertical: HEIGHT * 1.5,
    borderRadius: 5,
  },
  searchInputView: {
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F2F2',
    width: WIDTH * 90,
    paddingHorizontal: WIDTH * 3,
    height: 40,
  },
  inputView: {
    borderBottomWidth: 1,
    width: WIDTH * 90,
    alignSelf: 'center',
    borderBottomColor: 'red',
    height: 45,
  },
  editProfileIcon: {
    position: 'absolute',
    top: HEIGHT * 10,
    right: WIDTH * 0,
    alignSelf: 'center',
  },
  textInputView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: WIDTH * 4,
    marginTop: HEIGHT * 2,
    borderRadius: 5,
    backgroundColor: WHITE,
    paddingHorizontal: WIDTH * 3,
    height: 45,
  },
  reviewBox: {
    // backgroundColor: '#F2F2F2',
    borderRadius: 5,
    // marginTop: HEIGHT * 2,
    paddingHorizontal: WIDTH * 3,
    height: HEIGHT * 20,
    borderWidth: 1,
    borderColor: '#7C7C80' + 50,
  },
  emergencycallsView: {
    backgroundColor: WHITE,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: HEIGHT * 1,
    paddingHorizontal: WIDTH * 4,
    marginVertical: HEIGHT * 1,
  },
  txtinput: {
    // marginHorizontal: 15,
    // width: "80%",
    borderRadius: 5,
    borderWidth: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    // justifyContent: "space-around",
    borderColor: WHITE,
    height: 45,
  },
  otherApp: {
    backgroundColor: WHITE,
    elevation: 3,
    width: WIDTH * 43,
    borderRadius: 5,
  },
  visitTStyle: {
    height: 100,
    width: 100,
    alignSelf: 'center',
  },
  nearByView: {
    width: WIDTH * 63,
    backgroundColor: WHITE,
    elevation: 3,
    // borderBottomWidth: 1,
    borderRadius: 10,
    // borderBottomColor: 'gray',
    marginRight: WIDTH * 5,
  },
  starImagePositionView: {
    position: 'absolute',
    zIndex: 999,
    right: 10,
    top: 10,
  },
  levelView: {
    paddingHorizontal: WIDTH * 2,
    borderRadius: 5,
    paddingVertical: 3,
  },
  loginTopImage: {
    height: HEIGHT * 30,
    width: WIDTH * 100,
  },
  googleButton: {
    alignItems: 'center',
    paddingVertical: HEIGHT * 1.5,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'gray',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: HEIGHT * 5,
    alignSelf: 'center',
    width: WIDTH * 90,
  },
  verticleLineOtp: {
    height: 17,
    width: 1,
    backgroundColor: 'gray',
  },
  recommendedView: {
    height: HEIGHT * 20,
    width: WIDTH * 60,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginRight: WIDTH * 5,
  },
  recommendedMainView: {
    width: WIDTH * 60,
    backgroundColor: WHITE,
    borderRadius: 10,
    marginRight: WIDTH * 5,
    marginBottom: 10,
    marginLeft: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 3,
  },
  positionDarkview: {
    width: WIDTH * 90,
    height: 220,
    backgroundColor: BLACK,
    opacity: 0.3,
    position: 'absolute',
    borderRadius: 20,
  },

  // Wishlist
  wishlistMainView: {
    width: WIDTH * 90,
    backgroundColor: WHITE,
    borderRadius: 15,
    marginTop: HEIGHT * 3,
    marginHorizontal: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 3,
    marginBottom: 2,
  },
  wishlistImageView: {
    height: HEIGHT * 22,
    width: WIDTH * 90,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  coverImage: {
    width: WIDTH * 90,
    height: 180,
    borderRadius: 20,
    marginTop: 25,
  },
  coverImageBG: {
    height: 150,
    backgroundColor: BUILDRR_BLUE,
    position: 'absolute',
    width: '100%',
    top: 0,
  },

  // Profile

  ProfileCardView: {
    width: WIDTH * 89,
    borderRadius: 15,
    marginTop: HEIGHT * 1,
    paddingHorizontal: WIDTH * 3,
    paddingVertical: HEIGHT * 2,
    left: 2,
    top: 2,
    marginBottom: 10,
  },
  updateButton: {
    backgroundColor: BUILDRR_BLUE,
    alignItems: 'center',
    //  marginHorizontal: WI,
    paddingVertical: HEIGHT * 1.5,
    borderRadius: 5,
  },
  tabs: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F5F7FA',
    marginTop: 15,
    marginHorizontal: WIDTH * 1,
    borderRadius: 8,
    padding: 5,
  },
  activeTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    height: 40,
    borderBottomWidth: 2,
    borderBottomColor: BUILDRR_BLUE,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F7FA',
    height: 40,
    borderRadius: 6,
    borderBottomWidth: 2,
    borderBottomColor: '#F5F7FA',
  },
  searchInputViewSearch: {
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F2F2',
    width: WIDTH * 90,
    paddingHorizontal: WIDTH * 3,
    height: 45,
  },
  foodView: {
    backgroundColor: WHITE,
    borderColor: BUILDRR_BLUE,
    borderWidth: 1,
    paddingHorizontal: WIDTH * 4,
    paddingVertical: HEIGHT * 0.4,
    borderRadius: 90,
    marginRight: WIDTH * 2,
    marginTop: HEIGHT * 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  addImageView: {
    height: HEIGHT * 17,
    width: WIDTH * 90,
    borderRadius: 10,
    marginVertical: HEIGHT * 2,
  },
  whitHomeView: {
    backgroundColor: WHITE,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
    paddingBottom: HEIGHT * 2,
    marginVertical: HEIGHT * 2,
    marginHorizontal: WIDTH * 0.5,
  },
  addToPlanButton: {
    borderWidth: 1,
    borderColor: BUILDRR_BLUE,
    borderRadius: 10,
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nearYouImage: {
    height: 120,
    width: 120,
    borderRadius: 10,
  },
  nearYouCardView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  verticleLine: {
    height: 10,
    width: 1,
    backgroundColor: 'gray',
    marginHorizontal: 4,
  },
  rattingStar: {
    height: 16,
    width: 80,
  },
  distanceIcon: {
    width: 14,
    height: 12,
  },
  favIconView: {
    position: 'absolute',
    backgroundColor: WHITE,
    borderRadius: 90,
    height: 30,
    width: 30,
    zIndex: 9999,
    alignItems: 'center',
    justifyContent: 'center',
    right: 20,
    top: 10,
  },
  favIcon: {
    fontSize: 18,
    color: LIGHTGRAY,
  },
  activeFavIcon: {
    fontSize: 18,
    color: BUILDRR_BLUE,
  },
  rattingView: {
    backgroundColor: BUILDRR_BLUE,
    borderRadius: 5,
    paddingHorizontal: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginTopImage: {
    width: WIDTH * 90,
    height: 220,
    borderRadius: 20,
  },
  homeSwiperImage: {
    width: WIDTH * 90,
    height: 140,
    borderWidth: 4,
    borderColor: BUILDRR_BLUE,
    borderRadius: 20,
  },
  hotelNameView: {
    position: 'absolute',
    backgroundColor: BUILDRR_BLUE,
    top: 20,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 13,
  },
  swiperRview: {
    position: 'absolute',
    backgroundColor: WHITE,
    paddingHorizontal: 5,
    bottom: 12,
    right: 10,
    borderRadius: 5,
  },
  swiperPositionReview: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    borderRadius: 5,
  },
  catImage: {
    height: 60,
    width: 60,
    borderRadius: 15,
  },
  catImageView: {
    alignItems: 'center',
    justifyContent: 'center',
    width: WIDTH * 23,
    marginVertical: 10,
  },
  seeMoreTextView: {
    borderRadius: 5,
    borderColor: 'gray',
    backgroundColor: PRIMARY_COLOR,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  compneyProfileImageContainer: {
    borderRadius: 8,
    height: 100,
    width: 100,
    borderWidth: 4,
    backgroundColor: WHITE,
    borderColor: WHITE,
    justifyContent: 'center',
    alignSelf: 'center',
    position: 'absolute',
    top: -60,
  },
  compneyProfileImage: {
    borderRadius: 8,
    height: 90,
    width: 90,
    borderWidth: 2,
    justifyContent: 'center',
    alignSelf: 'center',
    borderColor: BUILDRR_BLUE,
  },
  clearButtonView: {
    height: 30,
    width: 65,
    alignItems: 'center',
    justifyContent: 'center',
  },
  aboutUsImage: {
    height: 160,
    width: '95%',
    borderRadius: 10,
    marginVertical: 10,
    marginHorizontal: 10,
  },
  profileImageView: {
    height: HEIGHT * 13,
    width: HEIGHT * 13,
    borderRadius: 90,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  profileImage: {
    alignSelf: 'center',
    height: HEIGHT * 13,
    width: HEIGHT * 13,
    borderRadius: 90,
    marginTop: HEIGHT * 2,
  },
  johnImage: {
    alignSelf: 'center',
    height: 80,
    width: 80,
    borderRadius: 10,
    marginTop: HEIGHT * 2,
  },
  logoutHeader: {
    backgroundColor: BUILDRR_BLUE,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    paddingVertical: HEIGHT * 1,
  },
  categoryImageView: {
    alignItems: 'center',
    justifyContent: 'center',
    width: WIDTH * 30,
    marginVertical: 10,
  },
  categoryImage: {
    height: 80,
    width: 80,
    borderRadius: 15,
    borderWidth: 1,
  },
  catTopImage: {
    height: 220,
    width: WIDTH * 90,
    borderRadius: 20,
    paddingHorizontal: 10,
    marginTop: HEIGHT * 2.5,
  },
  catOfferView: {
    position: 'absolute',
    left: 20,
    top: 35,
  },
  catRattingImage: {
    height: 12,
    width: 60,
  },
  swiperDotStyle: {
    backgroundColor: WHITE,
    height: 8,
    width: 8,
  },
  verticleLineInfo: {
    height: 20,
    width: 1,
    backgroundColor: 'gray',
  },
  infoProfileImage: {
    height: 50,
    width: 50,
    borderRadius: 10,
  },
  BUILDRR_BLUERattingView: {
    backgroundColor: BUILDRR_BLUE,
    borderRadius: 5,
    paddingHorizontal: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noData: {
    height: constants.BaseStyle.DEVICE_HEIGHT / 1.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listContainer: {
    flex: 1,
    padding: 20,
  },
  headerRightIconWrapper: {
    marginRight: 20,
  },
  marginRight10: {
    marginRight: 10,
  },
  marginTop10: {
    marginTop: 10,
  },
  backgroundWhite: {
    backgroundColor: 'transparent',
  },
  headerRightIcon: {
    height: 20,
  },
  headerBackIcon: {
    height: 15,
  },
  smallTopSpacing: {
    paddingTop: 2,
  },
  icon: {
    height: 15,
    width: 15,
    resizeMode: 'contain',
  },
  chatIcon: {
    height: 25,
    width: 25,
    resizeMode: 'contain',
  },
  iconWithItems: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconRightSpacing: {
    marginRight: 5,
  },
  chatWithMeContainer: {
    backgroundColor: PRIMARY_COLOR,
    borderRadius: 30,
    padding: 10,
    flex: 1,
    justifyContent: 'center',
  },
  grayWrapper: {
    backgroundColor: BGGRAY,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 30,
  },
  flatlistImage: {
    width: Dimensions.get('window').width / 2 - 40, // Adjust width as per your preference
    height: Dimensions.get('window').width / 2 - 70,
    marginBottom: 16,
    borderRadius: 10,
    resizeMode: 'cover',
  },
  imageWrapper: {
    ...Platform.select({
      ios: {
        shadowColor: 'black',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.3,
        shadowRadius: 4,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  okBtn: {
    paddingHorizontal: 30,
    paddingBottom: 10,
  },
  overlayContainer: {
    padding: 20,
  },
  galleryScrollWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    padding: 16,
  },
  galleryImg: {
    height: HEIGHT * 30,
    width: WIDTH * 50,
    resizeMode: 'contain',
  },
  iconWrapper: {
    height: 40,
    width: 40,
    backgroundColor: YELLOW,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  leftIcon: {
    height: 20,
    width: 20,
    tintColor: BUILDRR_BLUE,
  },
  rightIcon: {
    height: 22,
    width: 22,
    tintColor: BUILDRR_BLUE,
  },
  closeIcon: {
    position: 'absolute',
    right: 15,
    top: 15,
    zIndex: 9,
  },
  nextPrevBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    justifyContent: 'space-between',
  },
  modalWrapper: {
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 8
  },
  closeImage:{
    height: 30,
    width: 30
  },
  infoIcon:{
    height: 16,
    width: 16
  },
  openSettings: {
    position: 'absolute',
    bottom: 10,
    right: 25
  }
});
export default CommonStyles;
