const COLORS = {
  BLACK: '#000000',
  SPLASH_BLACK: '#1d1b1c',
  WHITE: '#FFFFFF',
  PRIMERY: '#FABE06',
  SECONDARY: '#304b9c',
  RED: '#DD4B39',
  DARK_GRAY: '#7C7C80',
  BUILDRR_BLUE: '#2ABCEE',
  GRAY: '#F2F2F2',
  TABCOLOR: '#F5F7FA',
  LIGHTGRAY: '#BBBBBB',
  BGGRAY: '#c6c6c6',
  PRIMARY_COLOR: '#097CAF',
  LIGHT_PRIMARY_COLOR: '#CCF2FF',
  YELLOW: '#FFDF05',
  GOLD: '#F8BE0C',
};
module.exports = COLORS;